### ISSUE TITLE
Installs but doesn't show on Work Item Form

### ISSUE THREAD

**Issue by scattergood** [ostreifel/Zen-Form#1]
Hi,

Your extension looks really great, but I can't get it to work.  I installed on my on-prem TFS but when I go to any work item, the Zen Page tab is missing. I am using TFS 2017 and have installed on the collection.

Please let me know what I can do to fix this or if you need any other information.

Thanks,
Josh

**Comment by ostreifel** [comment]
You need to first export the process template and then add the zen form to the work item template you want to have the zen form. It should be similar to setting up the [board group](https://marketplace.visualstudio.com/items?itemName=ottostreifel.board-group) except for pages instead of groups. After you have done that bump the process template version and import the process template back into the on premise installation.

Sorry for slow response I had forgotten to setup notifications for this repository.
