### ISSUE TITLE
Zen-Form update

### ISSUE THREAD

**Issue by seapeter** [ostreifel/Zen-Form#2]
Are there any plans to elaborate on the functionality of the Zen-Form extension.  We are currently using TFS On-Prem version 2017 update 3.1 and are intrigued by this idea.  A few items we noticed while testing the extension are:
1)	Exposes fields that are hidden, the fields don’t always sync to the current UI and Zen form allows you to modify read only fields. 
2)	Fields that are exposed don’t look and feel like they do in the current UI (e.g. – Description Field, one line text box).
3)	When moving columns, Fields become unstable and the logic doesn’t necessarily carry over.

**Comment by ostreifel** [comment]
As I kept think about all of the things that would need to be implemented to bring the zen form extension to parity with the existing form the amount of work that would be required kept ballooning. For this reason extension is not under active development.

Things that would be required for parity
- Check for readonly field
- Longtext/html field editors (medium feature)
- Comment paging/formatting (large)
- Build up a development control (very large)
- Build up a related work control  (very large)
- Identity pickers - not supported at all by the apis available (not possible)

After exploring the concept I don't think this a thing that should be an extension because I would just end up cloning so much of the logic that is built into the product.
